[package]
name = "typegen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1"
fancy-regex = "^0.13"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
toml = "^0.8"
walkdir = "2.5.0"
